language: objective-c

before_install:
    - gem update --system
    - gem install ios_ci
    - brew install ios-sim

script: ios_ci cedar --source-root ./ --target Specs

notifications:
  email:
    - 1101.debian@gmail.com
